// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnae17rzEMOf00xZOIWmhLkpcXSfjnXC8',
    appId: '1:260218359948:web:1ab070919e4f73c2c36ba9',
    messagingSenderId: '260218359948',
    projectId: 'us-chat-c7a94',
    authDomain: 'us-chat-c7a94.firebaseapp.com',
    storageBucket: 'us-chat-c7a94.firebasestorage.app',
    measurementId: 'G-JBX0ESE49Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSpyA0W3wi-obQlf_5KnN05UlRcplpzZg',
    appId: '1:260218359948:android:2a191b0d7a32787ec36ba9',
    messagingSenderId: '260218359948',
    projectId: 'us-chat-c7a94',
    storageBucket: 'us-chat-c7a94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7HcgCMny9qs8UaX9JZZglkL0A7BQl2Vo',
    appId: '1:260218359948:ios:6c5270f5fd5c700bc36ba9',
    messagingSenderId: '260218359948',
    projectId: 'us-chat-c7a94',
    storageBucket: 'us-chat-c7a94.firebasestorage.app',
    iosBundleId: 'com.example.us',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7HcgCMny9qs8UaX9JZZglkL0A7BQl2Vo',
    appId: '1:260218359948:ios:6c5270f5fd5c700bc36ba9',
    messagingSenderId: '260218359948',
    projectId: 'us-chat-c7a94',
    storageBucket: 'us-chat-c7a94.firebasestorage.app',
    iosBundleId: 'com.example.us',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnae17rzEMOf00xZOIWmhLkpcXSfjnXC8',
    appId: '1:260218359948:web:3e0a085a711ebffac36ba9',
    messagingSenderId: '260218359948',
    projectId: 'us-chat-c7a94',
    authDomain: 'us-chat-c7a94.firebaseapp.com',
    storageBucket: 'us-chat-c7a94.firebasestorage.app',
    measurementId: 'G-QM9R7M7QPK',
  );
}
